#!/bin/bash

set -e
# changing the Server hostname
#=============================
sudo hostnamectl set-hostname Jumper-Server-01

# updating the server
#====================
sudo apt update -y
sudo apt upgrade -y

# create a folder to mount to efs
#================================
mkdir -p /home/ubuntu/webserver

# Change webserver folder owner to ubuntu
sudo chown ubuntu:ubuntu /home/ubuntu/webserver


# installing EFS client dependencies
#====================================
sudo apt -y install nfs-common stunnel4 git binutils

# adding the efs acces point to fstab
#=====================================
sudo tee -a /etc/fstab > /dev/null <<EOF
fs-0830aab8df1548209.efs.us-east-2.amazonaws.com:/ /home/ubuntu/webserver nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0
EOF

# mount efs
#===========
sudo mount -a

# connect to datadog
#===================
DD_API_KEY=dd31303c0eba9e900d834666d3c2e08e \
DD_SITE="uk1.datadoghq.com" \
DD_APM_INSTRUMENTATION_ENABLED=host \
DD_DATA_STREAMS_ENABLED=true \
DD_PROFILING_ENABLED=auto \
DD_ENV=dev \
DD_APM_INSTRUMENTATION_LIBRARIES=java:1,python:4,js:5,php:1,dotnet:3,ruby:2 \
DD_LOGS_CONFIG_PROCESS_COLLECT_ALL=true \
bash -c "$(curl -L https://install.datadoghq.com/scripts/install_script_agent7.sh)"
